### ISSUE TITLE
[Epic] Production integration of cuBLAS, cuDNN, and Triton

### ISSUE THREAD

**Issue by allieculp** [openxla/openxla-nvgpu#28]
MS2 Epic level item - to track library integration work.

```[tasklist]
### P1 cuBLAS
- [ ] cuBLAS integration for GEMMs - needs owner
```

```[tasklist]
### P1 Triton
- [ ] Triton integration @ezhulenev 
- [ ] #54 
- [ ] #13848
```

```[tasklist]
### P2 cuDNN
- [ ] cuDNN for MHA (flash attention) integration
- [ ] https://github.com/openxla/openxla-nvgpu/issues/98
```

**Comment by allieculp** [comment]
Design update from @ezhulenev scheduled for tomorrow.

**Comment by allieculp** [comment]
@julianwa @mattwalsh I think we should rewrite this Epic to include:
P1 - Triton integration
P1 - cublas for GEMMs
P2 - cuDNN for MHA (flash attention)

what do you think?

**Comment by julianwa** [comment]
> I think we should rewrite this Epic to include: P1 - Triton integration P1 - cublas for GEMMs P2 - cuDNN for MHA (flash attention)
> 
> what do you think?

That's fine by me. Production integration of cuBLAS, cuDNN, and Triton.

**Comment by allieculp** [comment]
Updated per today's discussion.
@burmako Please help to add any tasks you are working on to the task list above.
@mattwalsh @julianwa to find an owner for cuBLAS integration work.

**Comment by allieculp** [comment]
Adding @vmurali who is picking up some cublas work.
